name: SayHello

on:
   push:
     branches:
       - develop
       - main
   
jobs:
  detect-branch:
     runs-on: ubuntu-latest

     steps:
       - name: Download Source
         uses: actions/checkout@v4
          
       - name: Say Hello Main
         if: ${{ github.ref == 'refs/heads/main' }}
         run: echo "Hello, main!"
         
       - name: Say Hello develop
         if: ${{ github.ref == 'refs/heads/develop' }}
         run: echo "Hello, Develop!"
      
