name: minify Hello 

on:
   push:
     branches:
       - develop
       - main

   pull_request_target:
     branches:
       - develop
       - main

jobs:

  minify:
      
     runs-on: ubuntu-latest
     
     permissions:
      contents: write

     steps:
       - uses: actions/checkout@v4

       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
            node-version: '23'  

       - name: Install minify
         run: npm install minify -g

       - name: Minify JavaScript
         run: | 
              for file in *.js; 
              do if [[ "$file" != *.min.js ]]; 
              then minify "$file" > "${file%.js}.min.js" 
              fi done

       - name: Commit minified file
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
            commit_message: "successful Minify js"
